services:
  web:
    image: ghcr.io/ziyad217/belisio-website:latest
    restart: unless-stopped
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.belisio.rule=Host(`belisio.de`) || Host(`www.belisio.de`)"
      - "traefik.http.routers.belisio.entrypoints=web,websecure"
      - "traefik.http.routers.belisio.tls=true"
      - "traefik.http.routers.belisio.tls.certresolver=mytlschallenge"
      - "traefik.http.services.belisio.loadbalancer.server.port=80"

networks:
  n8n_default:
    external: true
