server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /index.html {
        return 301 /;
    }

    location ~* ^(.+)\.html$ {
        return 301 $1;
    }

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
